/**
 * @typedef {object} ApiDiscogsReleasesType
 * @property {number} id id
 * @property {string} status status
 * @property {number} year year
 * @property {string} resource_url resource_url
 * @property {string} uri uri
 * @property {object[]} artists artists
 * @property {string} artists.name name
 * @property {string} artists.anv anv
 * @property {string} artists.join join
 * @property {string} artists.role role
 * @property {string} artists.tracks tracks
 * @property {number} artists.id id
 * @property {string} artists.resource_url resource_url
 * @property {string|undefined} artists_sort artists_sort
 * @property {object[]} labels labels
 * @property {string} labels.name name
 * @property {string} labels.catno catno
 * @property {string} labels.entity_type entity_type
 * @property {string} labels.entity_type_name entity_type_name
 * @property {number} labels.id id
 * @property {string} labels.resource_url resource_url
 * @property {any[]} series series
 * @property {object[]} companies companies
 * @property {string} companies.name name
 * @property {string} companies.catno catno
 * @property {string} companies.entity_type entity_type
 * @property {string} companies.entity_type_name entity_type_name
 * @property {number} companies.id id
 * @property {string} companies.resource_url resource_url
 * @property {object[]} formats formats
 * @property {string} formats.name name
 * @property {string} formats.qty qty
 * @property {string[]} formats.descriptions descriptions
 * @property {string} data_quality data_quality
 * @property {object} community community
 * @property {number} community.have have
 * @property {number} community.want want
 * @property {object} community.rating rating
 * @property {number} community.rating.count count
 * @property {number} community.rating.average average
 * @property {object} community.submitter submitter
 * @property {string} community.submitter.username username
 * @property {string} community.submitter.resource_url resource_url
 * @property {object[]} community.contributors contributors
 * @property {string} community.contributors.username username
 * @property {string} community.contributors.resource_url resource_url
 * @property {string} community.data_quality data_quality
 * @property {string} community.status status
 * @property {number} format_quantity format_quantity
 * @property {string} date_added date_added
 * @property {string} date_changed date_changed
 * @property {number} num_for_sale num_for_sale
 * @property {number} lowest_price lowest_price
 * @property {number} master_id master_id
 * @property {string} master_url master_url
 * @property {string} title title
 * @property {string} country country
 * @property {string} notes notes
 * @property {object[]} identifiers identifiers
 * @property {string} identifiers.type type
 * @property {string} identifiers.value value
 * @property {string} identifiers.description description
 * @property {object[]} videos videos
 * @property {string} videos.uri uri
 * @property {string} videos.title title
 * @property {string} videos.description description
 * @property {number} videos.duration duration
 * @property {boolean} videos.embed embed
 * @property {string[]} genres genres
 * @property {string[]} styles styles
 * @property {object[]} tracklist tracklist
 * @property {string} tracklist.position position
 * @property {string} tracklist.type_ type_
 * @property {string} tracklist.title title
 * @property {string} tracklist.duration duration
 * @property {object[]} tracklist.extraartists extraartists
 * @property {string} tracklist.extraartists.name name
 * @property {string} tracklist.extraartists.anv anv
 * @property {string} tracklist.extraartists.join join
 * @property {string} tracklist.extraartists.role role
 * @property {string} tracklist.extraartists.tracks tracks
 * @property {number} tracklist.extraartists.id id
 * @property {string} tracklist.extraartists.resource_url resource_url
 * @property {object[]} tracklist.artists artists
 * @property {string} tracklist.artists.name name
 * @property {string} tracklist.artists.anv anv
 * @property {string} tracklist.artists.join join
 * @property {string} tracklist.artists.role role
 * @property {string} tracklist.artists.tracks tracks
 * @property {number} tracklist.artists.id id
 * @property {string} tracklist.artists.resource_url resource_url
 * @property {object[]|undefined} extraartists extraartists
 * @property {string} extraartists.name name
 * @property {string} extraartists.anv anv
 * @property {string} extraartists.join join
 * @property {string} extraartists.role role
 * @property {string} extraartists.tracks tracks
 * @property {number} extraartists.id id
 * @property {string} extraartists.resource_url resource_url
 * @property {object[]} images images
 * @property {string} images.type type
 * @property {string} images.uri uri
 * @property {string} images.resource_url resource_url
 * @property {string} images.uri150 uri150
 * @property {number} images.width width
 * @property {number} images.height height
 * @property {string} thumb thumb
 * @property {number} estimated_weight estimated_weight
 * @property {boolean} blocked_from_sale blocked_from_sale
 */
