services:
  discogs-notification-on-new-items_container:
    build:
      context: ./
      dockerfile: ./Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - ../:/app_discogs-notification-on-new-items:rw
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 5000:5000
      - 3000:3000
    networks:
      - discogs-notification-on-new-items_network
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.9-jammy
    environment:
      MONGO_INITDB_ROOT_USERNAME: discogs-notification-on-new-items
      MONGO_INITDB_ROOT_PASSWORD: discogs-notification-on-new-items
    volumes:
      - ../data:/data/db
    ports:
      - 27017:27017
    networks:
      - discogs-notification-on-new-items_network

  mongo-express:
    image: mongo-express
    ports:
      - 5001:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: discogs-notification-on-new-items
      ME_CONFIG_MONGODB_ADMINPASSWORD: discogs-notification-on-new-items
      ME_CONFIG_MONGODB_URL: 'mongodb://discogs-notification-on-new-items:discogs-notification-on-new-items@mongo:27017/db?authSource=admin'
    networks:
      - discogs-notification-on-new-items_network
    depends_on:
      - mongo

networks:
  discogs-notification-on-new-items_network:
    driver: 'bridge'
